Update to support Python 3.10
- Update typing-related code for newer Python/mypy
- Old pyyaml uses dead code

File "/buildbot/run_unittests/build/src/tools/pyyaml/lib3/yaml/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'